version: '3.7'
services:
  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8090:80"
    depends_on:
      - php
      - cache

  db:
    container_name: db
    image: mariadb:10
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlysymfony
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: "always"
    ports:
      - "14000:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

  cache:
    container_name: se_cache
    image: redis:6.2-alpine
    restart: "no"
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
  cache:
    driver: local
###< doctrine/doctrine-bundle ###
