version: '3.7'
services:
  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8090:80"
    depends_on:
      - php

  db:
    container_name: db
    image: mariadb:10
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlysymfony
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: "always"
    ports:
      - "14000:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
